### ISSUE TITLE
Should we use special characters or HTML entities? 

### ISSUE THREAD

**Issue by Anykan** [dododex/translations#1]
Hi,

how it looks with letters like ä,ö,ü,ß
In german we have many of that. Can i use it or should i use
ae for ä
oe for ö
ue for ü
ss for ß

or canwe use html named entities like 
`&auml;` for ä

or anything else

greatings from germany

**Comment by Promixius** [comment]
I would like to know as well for danish with æøå

**Comment by danleveille** [comment]
For now, let's use the exact characters (ä) instead of the HTML entities (`&auml;`). 

The whole file will be revamped before it goes live, so I'll have to do formatting, escaping, and encoding anyway, so let's just use the actual characters to make it easier.
