### ISSUE TITLE
[PT/FR/DE/IT] toCustomizeMult needs to be updated

### ISSUE THREAD

**Issue by danleveille** [dododex/translations#11]
Hey guys, I've changed the English phrasing of `toCustomizeMult` since it referred to a button placement that has moved. [Here's the exact change](https://github.com/dododex/translations/commit/61a2cd9bb7e942837d8a50f1e56ff86459d529fa).

I'll try to avoid referring to relative locations in the future, but for now, we'll need to update the four translations: 
- [x] Portuguese 
- [x] French
- [x] German
- [ ] Italian

**Comment by DevilKwang** [comment]
Hello, I'm sorry if I wrote here, but I'm interested to help you to translate this app in Italy, I use this app and I find more bug in Italy, contact me :)

**Comment by danleveille** [comment]
@DevilKwang Heya! Glad to hear! On the [main project page](https://github.com/dododex/translations), you can read details about how to translate it. Italian is partially done, but there's still some items missing, if you'd like to help! 👍
