### ISSUE TITLE
Primary navigation buttons need shortening

### ISSUE THREAD

**Issue by danleveille** [dododex/translations#125]
In the latest version of the app, the primary navigation includes five items: **Info, Stats, Breeding, Tips, More**. Because these items are horizontal, they are really restricted on space. Some of the translations are very long. I've included a list of terms that are somewhat long. 

- Not all of them _need_ to be shortened, but if any of these have a shorter translation.
- If any of these words can be abbreviated and still be completely clear, please let me know. (For example, I use "stats" instead of "statistics" and "info" instead of "information")
- The terms "info" and "more" do not need to exactly translated. (For example, "more" could be translated to anything that implies "additional" or "extra")

In the comments, please comment if the word can be shortened or abbreviated. If not, please comment so I can mark it off.

![IMG_8362](https://user-images.githubusercontent.com/5267075/54729766-9585a800-4b42-11e9-8c49-e37ed76aa205.jpg)

**cs:**
- info: "Informace"

**de:**
- stats: "Statuswerte"

**es:**
- breeding: "Apareamiento"
- stats: "Estadísticas"
- tips: "Consejos"
- info: "Información"

**fr:**
- stats: "Statistiques"

**el:**
- breeding: "Ζευγάρωμα"
- more: "Περισσότερα"
- stats: "Στατιστικά"
- info: "Πληροφορίες"

**it:**
- breeding: "Allevamento"
- stats: "Statistiche"
- tips: "Suggerimenti"

**nl:**
- stats: "Statistieken"
- info: "Informatie"

**pl:**
- breeding: "Rozmnażanie"
- stats: "Statystyki"
- tips: "Sposoby"

**pt-br:**
- breeding: "Gestação"
- stats: "Estatísticas"

**ro:**
- breeding: "Reproducere"
- more: "Mai mult" (is there a one-word alternative?)
- stats: "Statistici"
- tips: "Sfaturile"

**ru:**
- breeding: "Разведение"
- more: "Дополнительная информация" (must be shortened)
- stats: "Характеристики"
- tips: "Советы"

**th:**
- breeding: "การผสมพันธุ์"

**tr:**
- more: "Daha Fazla" (is there a one-word alternative?)
- stats: "İstatistikler"

**PROGRESS**
- [ ] cs
- [ ] tr
- [x] fr
- [x] el
- [x] pl
- [x] ro
- [x] th
- [x] it
- [x] es
- [x] pt-br
- [x] de
- [x] nl
- [x] ru

**Comment by JoepGoossens04** [comment]
"Informatie" in Dutch can be abbreviaded to "info"

**Comment by EgoSilentium** [comment]
more: "Доп."
stats: "Хар-ки"

**Comment by TheRealestMVP** [comment]
For German (**de**):
- info: "Info" is perfectly fine, short for "Informationen"
- stats: "Statuswerte" could be shortened to "Werte". Or you could just leave "Stats" (not a german word exactly, but generally understood/known by gamers)
- breeding: "Züchten"
- tips: "Tipps"
- more: "Mehr"

**Comment by danleveille** [comment]
Got some feedback from other translators.

**PT-BR:** 
stats: Estat.

**DE:** 
info: "Info"
stats: "Stats" (A German translator suggested the English version would be understandable) 

**IT**
stats: "Stat" (An Italian translator said that while there wasn't a commonly used abbreviation in Italian like there is in English, it would likely be understood if you just shorten it to "Stat")

**Comment by danleveille** [comment]
**TH**

From a translator: 

> You can actually cut the first word and it still has the same meaning. "ผสมพันธุ์" is enough 
> Same with energy level. If it’s all the same to you, "พลัง" already means power and in gaming it’s intuitive from there. "ค่าพลัง" is energy value, so if you wanna trim there you can.

**Comment by danleveille** [comment]
**RO**
> Translators suggest that there are no good translations without using "stats", which may not be completely clear to non-English speakers:
https://www.reddit.com/r/romanian/comments/b6spxa/how_would_you_shorten_these_two_romanian_words/

**EL** 
> You could replace "ΠΛΗΡΟΦΟΡΙΕΣ" with the slightly shorter "ΙΔΙΟΤΗΤΕΣ" which translates to "properties"
(Would love some feedback on this!)

**PL** 
I've made all of these chages:
Ad. 1.: You can abbreviate to „Rozmn.” but it must be crystal clear from context otherwise you don’t know if you mean a verb, a noun, a adverb etc.
Ad. 2.: „Stat.”, same applies as above.
However, Polish generally doesn’t do abbreviations and it’s best to avoid them, especially if you’re working within an academic/professional context.
Ad. 3.: „Sposoby” translates to „methods” or „ways”. For „tips” I’d suggest going with „porady”.

**Comment by JB-W** [comment]
FR:
"Statistiques" can be shortened to "stats" as well ;)

**Comment by csoles54** [comment]
Fr:
Info= informations, can be shortened to "Infos"
Breeding= reproduction, you can short it to "repro"
Stats = statistiques, you can leave "stats" all French people will understand
Tips = conseil, there is no way to short it unfortunately
More = Plus
I hope that will help you

**Comment by danleveille** [comment]
@JB-W @csoles54 Completely missed this. Thank you!

**Comment by Potatosaurus1** [comment]
i know Lithuanian, and i can add this language
info-informacija, but you can keep info, ppl will understand
breeding- i would say dauginimas, it means multiply, there is no word that can say breeding without being a bad word.
stats- i would say statistika is a good word.
tips- patarimai, it cannot be shortened
if i am wrong, i am sorry, Lithuanian is my 2nd language
