### ISSUE TITLE
[Spanish] Some names translated wrong

### ISSUE THREAD

**Issue by danleveille** [dododex/translations#141]
A few users reported the following corrections with the translations. Could someone review if these are correct?

**Should not be translated:**
- Acatina is **Achatina**
- Boa Titan is **Titanoboa**
- Caballo is **Equus**
- Carcinos is **Karkinos**

**Wrong translation:**
- Elemental se piedra is **Golem de piedra**
- Fororrácido is **Ave del terror**

**Comment by Depinky** [comment]
I think you can now close this issue 👍
