### ISSUE TITLE
Translation issues and size adaption error

### ISSUE THREAD

**Issue by N0Dr4m4L4m4** [dododex/translations#199]
Hey there,

while using the Dododex i found some aspects that could be improved.

## Filters size adaption 
sorry for that big screen shot, but here you can see it more briefly
![Screenshot_20220107-162320_Dododex_LI](https://user-images.githubusercontent.com/22734072/148566445-b52ccae6-f860-4623-9b8e-fca987d0f0e9.jpg)

## Translation not able
e.g for the shadowmane its not able to translate some areas in dododex. Maybe this could also able in the future?
![Screenshot_20220107-162246_Dododex_LI](https://user-images.githubusercontent.com/22734072/148566862-ca50f34e-5786-4359-9e3f-6006a51621bc.jpg)

**Comment by danleveille** [comment]
* **Filters size adaption** -- Are you able to scroll these horizontally? If not, I can add that. Also, do you know any way to shorten any of those words? Like an abbreviation? For example, in English, "Knock Out" is "KO".
* **Translated description** -- Yeah, I need to add this. 
* **Translated items** -- I've been planning on adding this, but unfortunately, the app is not structured to do this right now. I need to completely restructure how the app is built. (FYI: The list of taming foods is simply text and is not connected to the actual items. For example, the app doesn't know that the "Simple Kibble" food is connected to the "Simple Kibble" item/recipe -- and the "Raw Meat" in the ingredient list of the recipe isn't connected to the actual Raw Meat item, so translating items isn't possible right now. Once I standardize them and make sure all instances of an item reference one item, I can translate that item and it will be translated across the app.

**Comment by Carotinbombe** [comment]
Hey there

actually i updated the german language to get a better understanding what it actually means. It should be better now!? Hope so. Anyway it would be a great small feature to scroll, because in other languages its not that easy to find a small word for that meaning. 

All other:
Well i can understand that, take your time. Thanks 😊🖐
