### ISSUE TITLE
Translations needed for App Name

### ISSUE THREAD

**Issue by danleveille** [dododex/translations#22]
Hey guys, I thought I'd open an issue for this one since this translation is very important and going to require some discussion. The app's name (iOS only) is **limited to 50 characters**. I took a stab at it for each language

The ideal name is:

> **Dododex Taming Calculator for Ark: Survival Evolved**

However, if that doesn't work, it can be shortened to "Dododex Taming Calculator - Ark: Survival Evolved". Keeping "Taming Calculator" is really ideal, but if absolutely impossible, it can be shortened to just "Dododex for Ark: Survival Evolved". But it's better to shorten it than for it to sound strange.
# Translations
### Spanish

Dododex Calculadora de Doma: Ark: Survival Evolved
### French

Dododex pour Ark: Survival Evolved

It doesn't seem possible to include "Calculateur de Dressage" in the title. "Dododex Calculateur Dressage: Ark Survival Evolved" doesn't work, does it? Does it need the "de"?
### German

Dododex Taming-Rechner fürf Ark: Survival Evolved
### Italian

Dododex Calcolatore Taming - Ark: Survival Evolved

"Taming Calculator" is currently translated as "Calcolatore del taming." Does "Calcolatore Taming" work? Or should it just be "Dododex per Ark: Survival Evolved"?
### Portuguese

Dododex para Ark: Survival Evolved
### Chinese

Dododex 驯服计算器 Ark: Survival Evolved

Google Translate seemed to indicate that the word "for" isn't needed in Chinese? Let me know if there are any issues with this translation. 
### Russian

Dododex для Ark: Survival Evolved

It seems impossible to fit "Калькулятор приручения" into Russian.
# Progress
- [ ] German
- [ ] Portuguese
- [x] French
- [ ] Spanish
- [ ] Russian
- [ ] Italian
- [x] Chinese (Simplified)

**Comment by Coulson51** [comment]
**Chinese**
This is In accordance with Chinese word order:
Dododex Ark: Survival Evolved 驯服计算器 or Dododex 方舟：生存进化驯服计算器
PS:The "方舟：生存进化" In translation from "Ark: Survival Evolved"

**Comment by Aimeric99** [comment]
@danleveille : French

Hi, without "de", "calculateur de dressage" has no sense. Furthermore, write "calculateur de dressage" right to "dododex" seems strange in french. I think the best translation is : "**Dododex : Calculateur de Dressage pour Ark : Survival Evolved**".

**Comment by danleveille** [comment]
@Coulson51 Thanks! When most people refer to Ark in Chinese, which do they more frequently say? "方舟：生存进化 " or "Ark: Survival Evolved"? I assumed that game titles would not be translated, but I want to do whatever is more common in that language.

@Aimeric99 Oops! I made an error. I meant 50 characters rather than 80. So "Dododex: Calculateur de Dressage pour Ark : Survival Evolved" would not fit. Does "**Dododex pour Ark: Survival Evolved**" work? I want to include the game's title so people know it's an app for Ark.

**Comment by Aimeric99** [comment]
@danleveille

Yes, it works

**Comment by Coulson51** [comment]
@danleveille 
The "方舟：生存进化 " is an official translation.You can see this link: http://steamcommunity.com/sharedfiles/filedetails/?id=774591397
it's a screenshot of Ark: Survival Evolved steam page in Chinese.
If you suggest that game titles would not be translated,it is also feasible.

**Comment by BiGR1pp3r** [comment]
To Portuguese that's good only Dododex para Ark. Because so long term to translate all.

**Comment by hector-romero** [comment]
For spanish, I would apply the same comment made for the french version, it sounds weird like that.
The ideal would be:
    Dododex: Calculadora de Doma para Ark: Survival Evolved
But that's too long.

I would suggest to go for:
    Dododex: Calculadora para Ark: Survival Evolved

The ideal already sounds a bit weird (Iorld 'Doma' sounds a bit weird for me at least)

**Comment by ZokRadonh** [comment]
German:

**Dododex Zähmungsrechner für Ark: Survival Evolved**
This would be the translation. 49 chars.
I would say that the german Ark community is familiar with the word "Taming" and would accept "Taming-Rechner" but this is not a german word and not a typical gaming word like "level" which is widely accepted as word which can be used in german texts in gaming context.

**Comment by EgoSilentium** [comment]
@danleveille 

Fixed for Russian translation!

**Comment by Noel12321** [comment]
hu: Dododex szelidítés számoló Ark survival evoled-hez

**Comment by Damianero33** [comment]
Polish: Dododex kalkulator oswajania Ark: Survival Evolved

**Comment by danleveille** [comment]
Moved this to the actual part of the translation file. :)
