### ISSUE TITLE
Need tanslation dino name

### ISSUE THREAD

**Issue by walk728** [dododex/translations#39]
Cant't tanslation dinos name , it's very inconvenient.

**Comment by Coulson51** [comment]
+1

**Comment by danleveille** [comment]
@walk728 @Coulson51 Thanks for the interest, guys! This will be coming sometime soon! I'll let you know when it's ready for translation! 😄

**Comment by danleveille** [comment]
In the meantime, if anyone wants to translate the dino names in advance, please do! 👍  Feel free to post the list of names on this thread!

**Comment by Coulson51** [comment]
@danleveille Already done :P 

Achatina           玛瑙螺
Allosaurus         异特龙
Angler             鮟鱇鱼
Ankylosaurus       甲龙
Araneo             蜘蛛
Archaeopteryx      始祖鸟
Argentavis         阿根廷巨鹰
Arthropluera       古马陆
Beelzebufo         魔鬼蛙
Brontosaurus       雷龙
Carbonemys         淡水碳龟
Carnotaurus        食肉牛龙
Castoroides        巨型河狸
Chalicotherium     砾爪兽
Compy              美颌龙
Dilophosaur        双脊龙
Dimetrodon         异齿龙
Dimorphodon        双齿翼龙
Diplocaulus        笠头螈
Diplodocus         梁龙
Direbear           凶暴熊
Direwolf           冰原狼
Dodo               渡渡鸟
Doedicurus         星尾兽
Dung Beetle        蜣螂
Dunkleosteus       邓氏鱼
Gallimimus         似鸡龙
Giganotosaurus     南方巨兽龙
Gigantopithecus    巨猿
Ichthy             鱼龙
Jerboa             跳鼠
Kairuku            凯鲁库企鹅
Kaprosuchus        猪鳄
Lymantria          毒蛾
Lystrosaurus       水龙兽
Mammoth            猛犸象
Manta              蝠鲼
Mantis             螳螂
Megaloceros        大角鹿
Megalodon          巨齿鲨
Megalosaurus       巨齿龙
Megapithecus       中猴
Morellatops        驼峰兽
Mosasaurus         沧龙 
Moschops           麝足兽
Onyc               巨型蝙蝠
Oviraptor          窃蛋龙
Pachy              肿头龙
Pachyrhinosaurus   厚鼻龙
Paracer            巨犀
Parasaur           副栉龙
Pelagornis         伪齿鸟
Phiomia            渐新象
Plesiosaur         蛇颈龙
Procoptodon        巨型短面袋鼠
Pteranodon         无齿翼龙
Pulmonoscorpius    普莫诺蝎
Quetzal            风神翼龙
Raptor             迅猛龙
Rex                霸王龙
Rock Elemental     石头人
Sabertooth         剑齿虎
Sarco              帝王鳄
Spinosaur          棘背龙
Spinosaur          剑龙
Tapejara           古神翼龙
Terror Bird        恐鸟
Thorny Dragon      棘手龙
Titanoboa          泰坦巨蟒
Titanosaur         泰坦龙
Triceratops        三角龙
Vulture            秃鹰
Woolly Rhino       披毛犀
Wyvern             双足飞龙

**Comment by danleveille** [comment]
@Coulson51 Thank you!! 😄

**Comment by walk728** [comment]
@danleveille If it's ready to add to the app? really needed these tanslation. dino's name is very complicated :(

**Comment by danleveille** [comment]
@walk728 I plan on implementing it, but I don't have an estimate of when it'll happen. I'm a single developer building the app so developing new features can take a while.

**Comment by GreatFireWall** [comment]
@danleveille Do you need some help for adding this feature (translation of dinos name) ?

**Comment by danleveille** [comment]
@GreatFireWall Yes, please share them here. :)

**Comment by GreatFireWall** [comment]
@danleveille,  @Coulson51 has shared them. My language is Chinese. :blush:

**Comment by EgoSilentium** [comment]
@danleveille All dinos in Russian

Achatina Ахатина
Allosaurus Аллозавр
Ammonite Аммонит
Angler Удильщик
Ankylosaurus Анкилозавр
Araneo Аранео
Archaeopteryx Археоптерикс
Argentavis Аргентавис
Arthropluera Артроплевра
Attack Drone Атакующий дрон
Baryonyx Барионикс
Basilosaurus Базилозавр
Beelzebufo Жаба
Brontosaurus Бронтозавр
Broodmother Lysrix Праматерь
Chalicotherium Халикотерий
Carbonemys Карбонемис
Carnotaurus Карнотавр
Castoroides Кастороидес
Cnidaria Книдария
Coelacanth Целакант
Compy Компсогнат
Daeodon Деодон
Deathworm Червь смерти
Defense Unit Защитная единица
Dilophosaur Дилофозавр
Dimetrodon Диметродон
Dimorphodon Диморфодон
Diplocaulus Диплокаулус
Diplodocus Диплодок
Direbear Свирепый медведь
Direwolf Лютоволк
Dodo Додо
Doedicurus Дедикурус
Dragon Дракон
Dung Beetle Скарабей
Dunkleosteus Дунклеостей
Electrophorus Электрофорус
Equus Эквус
Gallimimus Галлимим
Giant Bee Гигантская пчела
Giganotosaurus Гиганотозавр
Gigantopithecus Гигантопитек
Griffin Грифон
Hesperornis Гесперорнис
Hyaenodon Гиенодон
Ichthyornis Ихтиорнис
Ichthyosaurus Ихтиозавр
Iguanodon Игуанодон
Jerboa Тушканчик
Kairuku Кайруку
Kaprosuchus Капрозух
Kentrosaurus Кентрозавр
Leedsichthys Лидсихтис
Liopleurodon Лиоплевродон
Lymantria Шелкопряд
Lystrosaurus Листрозавр
Mammoth Мамонт
Manta Манта
Manticore Мантикора
Mantis Богомол
Megalania Мегалания
Megaloceros Большерогий олень
Megalodon Мегалодон
Megalosaurus Мегалозавр
Megapithecus Мегапитек
Megatherium Мегатерий
Mesopithecus Мезопитек
Microraptor Микрораптор
Morellatops Мореллатопс
Mosasaurus Мозазавр
Moschops Мосхопс
Onyc Оникониктерис
Otter Выдра
Overseer Надзиратель
Oviraptor Овираптор
Ovis Овис
Pachy Пахицефалозавр
Pachyrhinosaurus Пахиринозавр
Paraceratherium	 Парацератерий
Parasaur Паразауролоф
Pegomastax Пегомастакс
Pelagornis Пелагорнис
Phoenix Феникс
Phiomia Фиомия
Piranha Пиранья
Plesiosaur Плезиозавр
Procoptodon Прокоптодон
Pteranodon Птеранодон
Pulmonoscorpius Скорпион
Purlovia Пурловия
Quetzal Кетцалькоатль
Raptor Раптор
Rex Тираннозавр
Rock Elemental Горный элементаль
Sabertooth Саблезуб
Sabertooth Salmon Саблезубый лосось
Sarco Саркозух
Spinosaurus Спинозавр
Stegosaurus Стегозавр
Tapejara Тапежара
Terror Bird Ужасная птица
Therizinosaur Теризинозавр
Thorny Dragon Шипастый дракон
Thylacoleo Тилаколев
Titanoboa Титанобоа
Titanosaur Титанозавр
Triceratops Трицератопс
Trilobite Трилобит
Troodon Троодон
Tusoteuthis Тусотеутис
Vulture Гриф
Woolly Rhino Шерстистый носорог
Wyvern Виверна
Yutyrannus Ютираннус

In the application for the full collection there is not enough creature: Eurypterid (Эвриптерид).

**Comment by flokiras49** [comment]
Hi, Now in french:
Achatine
Allosaure
Angler Baudroie Abyssale 
Ankylosaure
Argentavis L' Argentin magnifique
Arthropluera 
Basilosaurus Lézard royal
Beelzebufo Grenouille du Diable
Brontosaure
Carnotausaure
Castoroïdes 
Dilophosaure
Dimétrodon 
Direbear Ours Sinistre
Direwolf Loup Sinistre
Dodo Dronte de Maurice
Dung Beetle Scarabée Bousier
Electrophorus Anguille électrique 
Giant Bee Abeille Géante 
Giganotosaure
Gigantopithecus Gigantopithèque
Griffin Griffon
Ichthyosaure
Jerboa Gerboise
Kairuku Manchot
Liopleurodon Pliosaure 
Lystrosaure
Mammouth 
Mégalocéros 
Mégalodon 
Mégalosaure
Mosasaure
Onyc Chauves-souris 
Otter Loutre
Ovis Mouton
Parasaure
Plésiosaure
Rock Elemental Golem Élémentaire 
Sabertooth Smilodon(Tigre à dent de sabre) 
Spinosaure
Terror Bird Oiseau de terreur
Thylacoleo Lion marsupial 
Titanosaure
Vulture Vautour
Woolly Rhino Rhinoceros Laineux
Wyvern Vouivre
Other same, edit come for news
Merci de votre attention.

**Comment by danleveille** [comment]
Hello everyone! Dino translations are now supported and will be coming within a few weeks!

Please see the new creatures.json file to add translations! 👍

**Comment by Chepechan** [comment]
How could I help whit the spanish traslate? By comment?

**Comment by danleveille** [comment]
@Chepechan Please add them this file: https://github.com/dododex/translations/blob/master/creatures.json

Cc: @flokiras49 

Thank you!

**Comment by danleveille** [comment]
I'm going to mark this task as closed since it's actually implemented now. 😄

**Comment by Damianero33** [comment]
Achatina Achatins
Allosaurus Alozaur
Angler Angler
Ankylosaurus Ankylozaur
Araneo Araneo
Archaeopteryx Archeopteryx
Argentavis Argentavis
Arthropluera Arthropluera
Beelzebufo Beelzebufo
Brontosaurus Brontozaur
Carbonemys Karbonemys
Carnotaurus Karnotaur
Castoroides Castoroides
Chalicotherium Chalicotherium
Compy Kompsognat
Dilophosaur Dilofozaur
Dimetrodon Dimetrodon
Dimorphodon Dimorfodon
Diplocaulus Diplodaculus
Diplodocus Diplodok
Direbear Direbear 
Direwolf Direwolt
Dodo Dodo
Doedicurus Doedicurus
Dung Beetle Żuk gnojad
Dunkleosteus Ryba pancerna
Gallimimus Galimimus
Giganotosaurus Giganotozaur
Gigantopithecus Gigantopitek
Ichthy Ichty
Jerboa Jerboa
Kairuku Kairuku
Kaprosuchus Kaprozuchus
Lymantria Ćma
Lystrosaurus Lystrozaur
Mammoth Mamut
Manta Manta
Mantis Modliszka
Megaloceros Megaloceros
Megalodon Megalodon
Megalosaurus Megalozaur
Megapithecus Megapitek
Morellatops Morellatops
Mosasaurus Mozozaur
Moschops Moschops
Onyc Onyk
Oviraptor Oviraptor
Pachy Pachy
Pachyrhinosaurus Pachyrhinosaurus
Paracer Paracer
Parasaur Parazaurolof
Pelagornis Pelagornis
Phiomia Phiomia
Plesiosaur Pleziozaur
Procoptodon Procoptodon
Pteranodon Pteranodon
Pulmonoscorpius Pulminoskorpion
Quetzal Quetzal
Raptor Raptor
Rex Rex
Rock Elemental 
Sabertooth Tygrys szablozębny
Sarco Sarkozuch
Spinosaur Spinozaur
Spinosaur Spinosaur
Tapejara Tapajeranodon
Terror Bird Phoarm
Thorny Dragon Smok ciernisty
Titanoboa Tytanoboa
Titanosaur Tytanozaur
Triceratops Tricerstops
Vulture Sęp
Woolly Rhino Nosorożec włochaty
Wyvern Wywerna
