### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by Houska11** [dododex/translations#62]
Hello, how can I open the file? I have downloaded it and there was no new languages in app. I downloaded zip opener and tried to extract it bit still nothing. What I need to do to run it in app?

**Comment by danleveille** [comment]
@Houska11 Hello! The translations are already built-in to the app. This is just the public listing of the languages so that volunteers can help translating the app. To switch your language, go to Settings in your Dododex app and choose your language. 😄

**Comment by Houska11** [comment]
I dont see Czech :-/

Dne 22. 1. 2018 23:47 napsal uživatel "Dan Leveille" <
notifications@github.com>:

@Houska11 <https://github.com/houska11> Hello! The translations are already
built-in to the app. This is just the public listing of the languages so
that volunteers can help translating the app. To switch your language, go
to Settings in your Dododex app and choose your language. 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dododex/translations/issues/62#issuecomment-359597098>,
or mute the thread

**Comment by danleveille** [comment]
@Houska11 Oh, yes, Czech, Thai, and Turkish will be in the next version of the app. :)

**Comment by Houska11** [comment]
Ok :-D Looking forward to it.
Thanks for help and have a nice day

Dne 23. 1. 2018 0:08 napsal uživatel "Dan Leveille" <
notifications@github.com>:
